package CutMachine.entity;
// Generated 31.12.2012 21:28:25 by Hibernate Tools 3.2.1.GA



/**
 * Capacity generated by hbm2java
 */
public class Capacity  implements java.io.Serializable {


     private CapacityId id;
     private Integer rani;
     private Integer odpoledni;
     private Integer nocni;
     private Integer volkap;

    public Capacity() {
    }

	
    public Capacity(CapacityId id) {
        this.id = id;
    }
    public Capacity(CapacityId id, Integer rani, Integer odpoledni, Integer nocni, Integer volkap) {
       this.id = id;
       this.rani = rani;
       this.odpoledni = odpoledni;
       this.nocni = nocni;
       this.volkap = volkap;
    }
   
    public CapacityId getId() {
        return this.id;
    }
    
    public void setId(CapacityId id) {
        this.id = id;
    }
    public Integer getRani() {
        return this.rani;
    }
    
    public void setRani(Integer rani) {
        this.rani = rani;
    }
    public Integer getOdpoledni() {
        return this.odpoledni;
    }
    
    public void setOdpoledni(Integer odpoledni) {
        this.odpoledni = odpoledni;
    }
    public Integer getNocni() {
        return this.nocni;
    }
    
    public void setNocni(Integer nocni) {
        this.nocni = nocni;
    }
    public Integer getVolkap() {
        return this.volkap;
    }
    
    public void setVolkap(Integer volkap) {
        this.volkap = volkap;
    }




}


