package CutMachine.entity;
// Generated 25.12.2012 11:45:30 by Hibernate Tools 3.2.1.GA



/**
 * Inputmaterial generated by hbm2java
 */
public class Inputmaterial  implements java.io.Serializable {


     private int cislozak;
     private String cislorol;
     private Integer sire;
     private Integer druhpap;
     private Integer delkrol;
     private String cisvyrobku;

    public Inputmaterial() {
    }

	
    public Inputmaterial(int cislozak) {
        this.cislozak = cislozak;
    }
    public Inputmaterial(int cislozak, String cislorol, Integer sire, Integer druhpap, Integer delkrol, String cisvyrobku) {
       this.cislozak = cislozak;
       this.cislorol = cislorol;
       this.sire = sire;
       this.druhpap = druhpap;
       this.delkrol = delkrol;
       this.cisvyrobku = cisvyrobku;
    }
   
    public int getCislozak() {
        return this.cislozak;
    }
    
    public void setCislozak(int cislozak) {
        this.cislozak = cislozak;
    }
    public String getCislorol() {
        return this.cislorol;
    }
    
    public void setCislorol(String cislorol) {
        this.cislorol = cislorol;
    }
    public Integer getSire() {
        return this.sire;
    }
    
    public void setSire(Integer sire) {
        this.sire = sire;
    }
    public Integer getDruhpap() {
        return this.druhpap;
    }
    
    public void setDruhpap(Integer druhpap) {
        this.druhpap = druhpap;
    }
    public Integer getDelkrol() {
        return this.delkrol;
    }
    
    public void setDelkrol(Integer delkrol) {
        this.delkrol = delkrol;
    }
    public String getCisvyrobku() {
        return this.cisvyrobku;
    }
    
    public void setCisvyrobku(String cisvyrobku) {
        this.cisvyrobku = cisvyrobku;
    }




}


