package CutMachine.entity;
// Generated 18.12.2012 13:29:40 by Hibernate Tools 3.2.1.GA



/**
 * Inputmaterial generated by hbm2java
 */
public class Inputmaterial  implements java.io.Serializable {


     private int cislozak;
     private String cislorol;
     private Integer sire;
     private Integer druhpap;

    public Inputmaterial() {
    }

	
    public Inputmaterial(int cislozak) {
        this.cislozak = cislozak;
    }
    public Inputmaterial(int cislozak, String cislorol, Integer sire, Integer druhpap) {
       this.cislozak = cislozak;
       this.cislorol = cislorol;
       this.sire = sire;
       this.druhpap = druhpap;
    }
   
    public int getCislozak() {
        return this.cislozak;
    }
    
    public void setCislozak(int cislozak) {
        this.cislozak = cislozak;
    }
    public String getCislorol() {
        return this.cislorol;
    }
    
    public void setCislorol(String cislorol) {
        this.cislorol = cislorol;
    }
    public Integer getSire() {
        return this.sire;
    }
    
    public void setSire(Integer sire) {
        this.sire = sire;
    }
    public Integer getDruhpap() {
        return this.druhpap;
    }
    
    public void setDruhpap(Integer druhpap) {
        this.druhpap = druhpap;
    }




}


