package CutMachine.entity;
// Generated 18.12.2012 13:29:40 by Hibernate Tools 3.2.1.GA



/**
 * Outputmaterial generated by hbm2java
 */
public class Outputmaterial  implements java.io.Serializable {


     private int cislozak;
     private Integer c1;
     private Integer c2;
     private Integer c3;
     private Integer c4;
     private Integer c5;
     private Integer c6;
     private Integer c7;
     private Integer c8;
     private Integer c9;
     private Integer c10;
     private Integer c11;

    public Outputmaterial() {
    }

	
    public Outputmaterial(int cislozak) {
        this.cislozak = cislozak;
    }
    public Outputmaterial(int cislozak, Integer c1, Integer c2, Integer c3, Integer c4, Integer c5, Integer c6, Integer c7, Integer c8, Integer c9, Integer c10, Integer c11) {
       this.cislozak = cislozak;
       this.c1 = c1;
       this.c2 = c2;
       this.c3 = c3;
       this.c4 = c4;
       this.c5 = c5;
       this.c6 = c6;
       this.c7 = c7;
       this.c8 = c8;
       this.c9 = c9;
       this.c10 = c10;
       this.c11 = c11;
    }
   
    public int getCislozak() {
        return this.cislozak;
    }
    
    public void setCislozak(int cislozak) {
        this.cislozak = cislozak;
    }
    public Integer getC1() {
        return this.c1;
    }
    
    public void setC1(Integer c1) {
        this.c1 = c1;
    }
    public Integer getC2() {
        return this.c2;
    }
    
    public void setC2(Integer c2) {
        this.c2 = c2;
    }
    public Integer getC3() {
        return this.c3;
    }
    
    public void setC3(Integer c3) {
        this.c3 = c3;
    }
    public Integer getC4() {
        return this.c4;
    }
    
    public void setC4(Integer c4) {
        this.c4 = c4;
    }
    public Integer getC5() {
        return this.c5;
    }
    
    public void setC5(Integer c5) {
        this.c5 = c5;
    }
    public Integer getC6() {
        return this.c6;
    }
    
    public void setC6(Integer c6) {
        this.c6 = c6;
    }
    public Integer getC7() {
        return this.c7;
    }
    
    public void setC7(Integer c7) {
        this.c7 = c7;
    }
    public Integer getC8() {
        return this.c8;
    }
    
    public void setC8(Integer c8) {
        this.c8 = c8;
    }
    public Integer getC9() {
        return this.c9;
    }
    
    public void setC9(Integer c9) {
        this.c9 = c9;
    }
    public Integer getC10() {
        return this.c10;
    }
    
    public void setC10(Integer c10) {
        this.c10 = c10;
    }
    public Integer getC11() {
        return this.c11;
    }
    
    public void setC11(Integer c11) {
        this.c11 = c11;
    }




}


