package CutMachine.entity;
// Generated 18.12.2012 13:29:40 by Hibernate Tools 3.2.1.GA



/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private int id;
     private String state;

    public State() {
    }

	
    public State(int id) {
        this.id = id;
    }
    public State(int id, String state) {
       this.id = id;
       this.state = state;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


