package cutplanner.entity;
// Generated 14.12.2012 17:06:32 by Hibernate Tools 3.2.1.GA



/**
 * Druhpapiru generated by hbm2java
 */
public class Druhpapiru  implements java.io.Serializable {


     private int cislopap;
     private String druhpap;

    public Druhpapiru() {
    }

	
    public Druhpapiru(int cislopap) {
        this.cislopap = cislopap;
    }
    public Druhpapiru(int cislopap, String druhpap) {
       this.cislopap = cislopap;
       this.druhpap = druhpap;
    }
   
    public int getCislopap() {
        return this.cislopap;
    }
    
    public void setCislopap(int cislopap) {
        this.cislopap = cislopap;
    }
    public String getDruhpap() {
        return this.druhpap;
    }
    
    public void setDruhpap(String druhpap) {
        this.druhpap = druhpap;
    }




}


