package cutplanner.entity;
// Generated 14.12.2012 17:06:32 by Hibernate Tools 3.2.1.GA



/**
 * Responsibility generated by hbm2java
 */
public class Responsibility  implements java.io.Serializable {


     private int cislozak;
     private Integer osoba;

    public Responsibility() {
    }

	
    public Responsibility(int cislozak) {
        this.cislozak = cislozak;
    }
    public Responsibility(int cislozak, Integer osoba) {
       this.cislozak = cislozak;
       this.osoba = osoba;
    }
   
    public int getCislozak() {
        return this.cislozak;
    }
    
    public void setCislozak(int cislozak) {
        this.cislozak = cislozak;
    }
    public Integer getOsoba() {
        return this.osoba;
    }
    
    public void setOsoba(Integer osoba) {
        this.osoba = osoba;
    }




}


